### ISSUE TITLE
ipmitool sdr type 'Power Supply'|grep 'Presence detected'

### ISSUE THREAD

**Issue by yxxhero** [bougou/go-ipmi#32]
how to get same result by using the library? thanks so much.

**Comment by bougou** [comment]
You can refer to [`GetSensors`](https://github.com/bougou/go-ipmi/blob/v0.5.6/cmd/goipmi/commands/sdr.go#L150) method and Sensor's [`HumanStr`](https://github.com/bougou/go-ipmi/blob/v0.5.6/types_sensor.go#L1164) method (since from v0.5.6).

The "Presence detected" string for "Power Supply" type sensors just means the specific discrete event number(offset) is set/active for the sensor.

You can get discrete active events (number) of a sensor by Sensor's [`DiscreteActiveEvents`](https://github.com/bougou/go-ipmi/blob/v0.5.6/types_sensor.go#L1247) method and then get the  event string correspoding to the event number by Sensor's [`EventString`](https://github.com/bougou/go-ipmi/blob/v0.5.6/types_sensor.go#L1265) method.
